trigger: none

parameters:
  - name: imageTag
    displayName: 'Enter nanopipeline-build-environment image tag from last build https://dev.azure.com/Nanostring/Gemini/_build?definitionId=525&_a=summary'
    default: '1.3.2-94008'
    type: string

resources:
- repo: self

variables:
  group: smida-build-pipeline-devnext-variables

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build_image
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: smida-build-pipeline-devnext-variables
    steps:
    - task: ECRPullImage@1
      displayName: Pull NanoPipeline Build environment image from DEVNEXT HUB ECR
      inputs:
        awsCredentials: 'atomx-aws-devnext-hub'
        regionName: '$(AWS_REGION)'
        repository: 'ecr-cac1-devnext-cosmx_da_repo-devnext-hub-smida-nanopipeline-build-environment'
        imageSource: 'imagetag'
        imageTag: ${{ parameters.imageTag }}
    - task: Bash@3
      displayName: Run smida-nanopipeline-build-environment Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker run --rm -v "$(Build.SourcesDirectory)":"/source" $(DEVNEXT_HUB_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/ecr-cac1-devnext-cosmx_da_repo-devnext-hub-smida-nanopipeline-build-environment:${{ parameters.imageTag }}
    - task: Bash@3
      displayName: Copy .tar.gz file as latest
      inputs:
        targetType: 'inline'
        script: |
          cp *.tar.gz smiCellTyping_latest.tar.gz
    - task: S3Upload@1
      displayName: Upload CellTyping .tar.gz files to S3 on DEVNEXT HUB
      inputs:
        awsCredentials: 'atomx-aws-devnext-hub'
        regionName: '$(AWS_REGION)'
        bucketName: 's3-cac1-devnext-smida-assets-global-devnext'
        sourceFolder: '$(Build.SourcesDirectory)'
        globExpressions: '+(smiCellTyping|InSituType)_*.tar.gz'
        targetFolder: 'smida/assets/nanopipeline'