# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sum from negative binomial density function
#'
#' Probability density function of the negative binomial distribution (written in C++)
#'
#' @param mat dgCMatrix expression counts
#' @param s numeric scaling factor
#' @param x numeric expression for reference profile
#' @param bg numeric background level
#' @param size_dnb int Dispersion parameter
#'
#' @return rowSums for matrix of densities
#' @useDynLib InSituType, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @exportPattern "^[[:alpha:]]+" 
#' @export
lls <- function(mat, s, x, bg, size_dnb) {
    .Call(`_InSituType_lls`, mat, s, x, bg, size_dnb)
}

