# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' negative binomial density function
#'
#' Probability density function of the negative binomial distribution (written in C++)
#'
#' @param x dgCMatrix of quantiles
#' @param mu matrix containing Mean of the distribution 
#' @param size_dnb Dispersion parameter
#'
#' @return matrix of densities
#' @useDynLib MLEcell, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @exportPattern "^[[:alpha:]]+" 
#' @export
dnbinom_sparse <- function(x, mu, size_dnb) {
    .Call(`_MLEcell_dnbinom_sparse`, x, mu, size_dnb)
}

